# Generated by Django 2.1.4 on 2019-04-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('process', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('process', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20, unique=True)),
                ('userPasswd', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('userToken', models.CharField(max_length=50)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
