# Generated by Django 2.1.4 on 2019-06-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20, verbose_name='卡号')),
                ('userName', models.CharField(max_length=20, verbose_name='姓名')),
                ('process', models.CharField(max_length=20, verbose_name='工序')),
                ('code', models.CharField(max_length=50, verbose_name='二维码')),
                ('serial_number', models.CharField(max_length=50, verbose_name='流水号')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '扫码记录管理',
                'verbose_name_plural': '扫码记录',
                'ordering': ['-createTime'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=50, unique=True, verbose_name='机器码')),
                ('department', models.CharField(max_length=20, verbose_name='工序')),
                ('station', models.CharField(max_length=20, verbose_name='工位')),
                ('workshop', models.CharField(max_length=20, verbose_name='车间')),
                ('path', models.CharField(max_length=20, verbose_name='路径')),
            ],
            options={
                'verbose_name': '设备管理',
                'verbose_name_plural': '设备表',
            },
        ),
        migrations.CreateModel(
            name='Status_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('process', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '员工状态管理',
                'verbose_name_plural': '员工状态',
                'ordering': ['-createTime'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=20, unique=True, verbose_name='机器码')),
                ('userName', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
