# Generated by Django 2.1.4 on 2019-06-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_record',
            name='station',
            field=models.CharField(default='', max_length=20, verbose_name='工位'),
        ),
        migrations.AddField(
            model_name='status_record',
            name='station',
            field=models.CharField(default='', max_length=20, verbose_name='工位'),
        ),
    ]
