# Generated by Django 2.1.4 on 2019-07-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0003_auto_20190630_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='path',
            field=models.CharField(choices=[('cdf_clothes', '裁剪大货辅料衣服'), ('cdf_trousers', '裁剪大货辅料裤子'), ('cdl_clothes', '裁剪大货里布衣服'), ('cdl_trousers', '裁剪大货里布裤子'), ('cdm_clothes', '裁剪大货面料衣服'), ('cdm_trousers', '裁剪大货面料裤子'), ('serial_number', '编号子流程'), ('sample_clothes', '样衣')], max_length=20, verbose_name='路径'),
        ),
    ]
