# Generated by Django 2.1.4 on 2019-07-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0004_auto_20190701_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_bxd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=50, unique=True, verbose_name='视频名称')),
                ('process', models.CharField(max_length=20, verbose_name='工序')),
                ('file', models.FileField(upload_to='video', verbose_name='视频选择')),
            ],
            options={
                'verbose_name_plural': '视频表',
                'verbose_name': '视频管理',
            },
        ),
    ]
