# Generated by Django 2.1.4 on 2019-07-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0005_video_bxd'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_record',
            name='So',
            field=models.CharField(default='', max_length=50, verbose_name='订单号'),
        ),
        migrations.AddField(
            model_name='code_record',
            name='customer',
            field=models.CharField(default='', max_length=50, verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='status_record',
            name='reason',
            field=models.CharField(default='', max_length=20),
        ),
    ]
