# Generated by Django 2.1.4 on 2019-07-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0006_auto_20190709_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_record',
            name='Mo',
            field=models.CharField(default='', max_length=50, verbose_name='生产制造订单'),
        ),
        migrations.AddField(
            model_name='code_record',
            name='num',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
    ]
